/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#00daf3",
        "on-background": "#dce1fb",
        "on-tertiary-fixed": "#0b1c30",
        "on-secondary-container": "#a8afff",
        "outline-variant": "#3b494c",
        "surface-container": "#191f31",
        "inverse-primary": "#006875",
        "inverse-on-surface": "#2a3043",
        "on-surface": "#dce1fb",
        "on-primary": "#00363d",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004f58",
        "tertiary": "#e4edff",
        "secondary-fixed": "#e0e0ff",
        "on-surface-variant": "#bac9cc",
        "on-secondary-fixed-variant": "#343d96",
        "primary": "#c3f5ff",
        "surface-variant": "#2e3447",
        "secondary-container": "#343d96",
        "on-secondary-fixed": "#000767",
        "on-secondary": "#1b247f",
        "surface-container-highest": "#2e3447",
        "secondary": "#bdc2ff",
        "primary-container": "#00e5ff",
        "surface-container-low": "#151b2d",
        "error": "#ffb4ab",
        "primary-fixed": "#9cf0ff",
        "primary-fixed-dim": "#00daf3",
        "outline": "#849396",
        "on-primary-fixed": "#001f24",
        "surface-bright": "#33394c",
        "tertiary-fixed": "#d3e4fe",
        "on-tertiary-fixed-variant": "#38485d",
        "inverse-surface": "#dce1fb",
        "surface-container-lowest": "#070d1f",
        "on-error": "#690005",
        "on-primary-container": "#00626e",
        "tertiary-container": "#c1d2ec",
        "on-tertiary-container": "#4a5a70",
        "background": "#0c1324",
        "surface-container-high": "#23293c",
        "surface-dim": "#0c1324",
        "surface": "#0c1324",
        "secondary-fixed-dim": "#bdc2ff",
        "on-tertiary": "#213145",
        "tertiary-fixed-dim": "#b7c8e1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "container-margin-mobile": "20px",
        "gutter": "24px",
        "container-margin-desktop": "48px",
        "section-gap": "40px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "body-sm": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg-mobile": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
